### ISSUE TITLE
RST pin is not connected to any header pin

### ISSUE THREAD

**Issue by alsaleem00** [mcauser/MCUDEV_DEVEBOX_H7XX_M#3]
I just received the H750 board.
ST-LINK V2 requires to connect RST (reset pin) in order to do reset and start programming automatically.
However the board does not extend RST pin to any header pin.

As this can not be solved with current board, We recommend that developer extends RST to a header pin.
I recommend also to make RST available on SWD header as this is the mostly used scenario.
Second, we can not solve this issue now with soldering a pin because developer did not leave any spare pin on headers!

**Comment by mcauser** [comment]
FYI, you can contact the developer at: https://mcudev.taobao.com/

**Comment by mcauser** [comment]
From memory, you can flash it without a reset pin using a ST-Link V2.
Just need 4 pins: GND, 3V3, SWDIO, SWCLK
You need to connect BOOT0 to 3V3 to boot the board in the correct mode for flashing.

**Comment by alsaleem00** [comment]
thanks
