### ISSUE TITLE
128k flash, but 'firmware1.bin' is 448004 bytes length

### ISSUE THREAD

**Issue by eurol** [mcauser/MCUDEV_DEVEBOX_H7XX_M#6]
Hi!
Who can explain this?
743VIT has 2M, it is ok, no questions.
750VBT has 128k flash.
How is it possible to program it with 400k+ of code?
Or what am I missing?

**Comment by fa1ke5** [comment]
750 and 743 have 2Mb flash, but in 750 have software block all bank over 0s. ST-LINK utility flashing all 2mb and you can use ful size of internal flash.

**Comment by eurol** [comment]
Thank you for answer.
I thought memory is blocked because it does not work.
Can I use 2MB on any 750VBT or should I check it's memory blocks?

> 
> 
> 750 and 743 have 2Mb flash, but in 750 have software block all bank over 0s. ST-LINK utility flashing all 2mb and you can use ful size of internal flash.
